#!/usr/bin/env python3
"""Collect results/*/*/summary.json into RESULTS.md.

    python compare.py [--include-debug]
"""

import json
import argparse
from pathlib import Path
from collections import defaultdict

import numpy as np

from segpipe.data import CLASS_NAMES

ORGANS = CLASS_NAMES[1:]


def load_runs(root: Path, include_debug: bool) -> list[dict]:
    runs = []
    for path in sorted(root.glob("*/*/summary.json")):
        summary = json.loads(path.read_text())
        if summary.get("debug") and not include_debug:
            continue
        runs.append(summary)
    return runs


def fmt(values, digits=3) -> str:
    values = [v for v in values if v is not None]
    if not values:
        return ""
    if len(values) == 1:
        return f"{values[0]:.{digits}f}"
    return f"{np.mean(values):.{digits}f} ± {np.std(values):.{digits}f}"


def build_report(runs: list[dict]) -> str:
    lines = ["# Results", "", "Generated by `python compare.py`. Do not edit by hand; rerun it after a merge conflict.", ""]
    if not runs:
        return "\n".join(lines + ["_No runs yet._", ""])

    groups = defaultdict(list)  # (experiment, split) -> summaries
    for s in runs:
        groups[(s["experiment"], s["split"])].append(s)

    def metric_3d(s, name, organ=None):
        m = s.get("metrics_3d", {}).get(name)
        if m is None:
            return None
        return m["mean"] if organ is None else m["per_class"][organ]

    def dice_3d(s, organ=None):
        return metric_3d(s, "dice", organ)

    def delta(key, value, digits=3):
        reference = [value(s) for s in groups.get(("current", key[1]), [])]
        own = [value(s) for s in groups[key]]
        reference, own = [v for v in reference if v is not None], [v for v in own if v is not None]
        if key[0] == "current" or not reference or not own:
            return ""
        return f"{np.mean(own) - np.mean(reference):+.{digits}f}"

    header = ["Experiment", "Split", "Runs", "Owner", "2D val Dice", "Δ 2D", "3D Dice", "Δ 3D"] \
        + [f"3D {o}" for o in ORGANS] + ["Idea"]
    lines += ["Dice at the best epoch (chosen on 2D val Dice), mean over the 4 organs (± std over runs). "
              "Δ is against `current` on the same split.", "",
              "| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
    for key in sorted(groups):
        experiment, split = key
        members = groups[key]
        cells = [experiment, split, str(len(members)), members[0].get("owner") or "",
                 fmt([s["val_dice_2d"] for s in members]), delta(key, lambda s: s["val_dice_2d"]),
                 fmt([dice_3d(s) for s in members]), delta(key, dice_3d)]
        cells += [fmt([dice_3d(s, o) for s in members]) for o in ORGANS]
        cells += [members[0].get("idea") or ""]
        lines.append("| " + " | ".join(cells) + " |")

    # 3D boundary metrics (only shown if any run has them): HD95 / ASSD in mm
    # (lower is better), NSD as a fraction (higher is better). digits: 2 for the
    # mm distances, 3 for the NSD fraction.
    boundary = [("hd95", "HD95 (mm)", 2), ("assd", "ASSD (mm)", 2), ("nsd", "NSD@1mm", 3), ("nsd3", "NSD@3mm", 3)]
    if any(metric_3d(s, name) is not None for s in runs for name, _, _ in boundary):
        header = ["Experiment", "Split", "Runs"]
        for _, label, _ in boundary:
            header += [label, f"Δ {label}"]
        lines += ["", "3D boundary metrics at the best epoch, mean over the 4 organs (± std over runs). "
                  "HD95/ASSD are in mm (lower is better); NSD is the fraction of surface within 1 or 3 mm (higher is better). "
                  "Δ is against `current` on the same split.", "",
                  "| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
        for key in sorted(groups):
            experiment, split = key
            members = groups[key]
            cells = [experiment, split, str(len(members))]
            for name, _, digits in boundary:
                cells += [fmt([metric_3d(s, name) for s in members], digits),
                          delta(key, lambda s, n=name: metric_3d(s, n), digits)]
            lines.append("| " + " | ".join(cells) + " |")

        # Per-organ HD95 (mm, lower is better): shows where boundary error
        # concentrates (typically the thin, low-contrast esophagus).
        header = ["Experiment", "Split", "Runs"] + [f"HD95 {o}" for o in ORGANS]
        lines += ["", "Per-organ HD95 (mm) at the best epoch, mean ± std over runs (lower is better).", "",
                  "| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
        for key in sorted(groups):
            experiment, split = key
            members = groups[key]
            cells = [experiment, split, str(len(members))]
            cells += [fmt([metric_3d(s, "hd95", o) for s in members], 2) for o in ORGANS]
            lines.append("| " + " | ".join(cells) + " |")

    # Post-processing (eval.postprocess / eval_run.py --postprocess): the same predictions
    # scored raw and post-processed, so Δ is the effect of the post-processing alone.
    def post_3d(s, name):
        m = s.get("metrics_3d_post", {}).get(name)
        return None if m is None else m["mean"]

    post_groups = {key: [s for s in members if "metrics_3d_post" in s] for key, members in groups.items()}
    post_groups = {key: members for key, members in post_groups.items() if members}
    if post_groups:
        post_metrics = [("dice", "Dice", 3), ("hd95", "HD95 (mm)", 2), ("assd", "ASSD (mm)", 2), ("nsd", "NSD@1mm", 3), ("nsd3", "NSD@3mm", 3)]
        header = ["Experiment", "Split", "Runs", "Post-processing"]
        for _, label, _ in post_metrics:
            header += [f"{label} raw", f"{label} post", "Δ"]
        lines += ["", "Post-processing of the stitched 3D predictions: raw vs post-processed scores of the "
                  "same runs (mean over the 4 organs). Δ = post - raw.", "",
                  "| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
        for key in sorted(post_groups):
            experiment, split = key
            members = post_groups[key]
            cells = [experiment, split, str(len(members)), ", ".join(map(str, members[0].get("postprocess") or []))]
            for name, _, digits in post_metrics:
                raw = [metric_3d(s, name) for s in members]
                post = [post_3d(s, name) for s in members]
                pairs = [(r, p) for r, p in zip(raw, post) if r is not None and p is not None]
                cells += [fmt(raw, digits), fmt(post, digits),
                          f"{np.mean([p - r for r, p in pairs]):+.{digits}f}" if pairs else ""]
            lines.append("| " + " | ".join(cells) + " |")

    header = ["Experiment", "Run", "2D val Dice", "3D Dice", "3D HD95", "Best epoch", "Minutes", "Commit", "Device"]
    lines += ["", "## Runs", "", "| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
    for s in sorted(runs, key=lambda r: (r["experiment"], r["run"])):
        git = s.get("git") or {}
        commit = f"{git.get('commit')}{'*' if git.get('dirty') else ''}"
        lines.append("| " + " | ".join([s["experiment"], s["run"], fmt([s["val_dice_2d"]]), fmt([dice_3d(s)]),
                                        fmt([metric_3d(s, "hd95")], 2),
                                        f"{s['best_epoch']} / {s['epochs']}", str(s["train_minutes"]),
                                        commit, s["device"]]) + " |")
    lines += ["", "`*` = run made with uncommitted changes.", ""]
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Compare runs and write RESULTS.md")
    parser.add_argument("--results", type=Path, default=Path("results"))
    parser.add_argument("--output", type=Path, default=Path("RESULTS.md"))
    parser.add_argument("--include-debug", action="store_true")
    args = parser.parse_args()

    runs = load_runs(args.results, args.include_debug)
    args.output.write_text(build_report(runs))
    print(f"> Wrote {args.output} ({len(runs)} runs)")


if __name__ == "__main__":
    main()
