#!/usr/bin/env python3
"""Collect results/*/*/summary.json into RESULTS.md.

    python compare.py [--include-debug]
"""

import json
import argparse
from pathlib import Path
from collections import defaultdict

import numpy as np

from segpipe.data import CLASS_NAMES

ORGANS = CLASS_NAMES[1:]


def load_runs(root: Path, include_debug: bool) -> list[dict]:
    runs = []
    for path in sorted(root.glob("*/*/summary.json")):
        summary = json.loads(path.read_text())
        if summary.get("debug") and not include_debug:
            continue
        runs.append(summary)
    return runs


def fmt(values, digits=3) -> str:
    values = [v for v in values if v is not None]
    if not values:
        return ""
    if len(values) == 1:
        return f"{values[0]:.{digits}f}"
    return f"{np.mean(values):.{digits}f} ± {np.std(values):.{digits}f}"


def build_report(runs: list[dict]) -> str:
    lines = ["# Results", "", "Generated by `python compare.py`. Do not edit by hand; rerun it after a merge conflict.", ""]
    if not runs:
        return "\n".join(lines + ["_No runs yet._", ""])

    groups = defaultdict(list)  # (experiment, split) -> summaries
    for s in runs:
        groups[(s["experiment"], s["split"])].append(s)

    def dice_3d(s, organ=None):
        m = s.get("metrics_3d", {}).get("dice")
        if m is None:
            return None
        return m["mean"] if organ is None else m["per_class"][organ]

    def delta(key, value):
        reference = [value(s) for s in groups.get(("current", key[1]), [])]
        own = [value(s) for s in groups[key]]
        reference, own = [v for v in reference if v is not None], [v for v in own if v is not None]
        if key[0] == "current" or not reference or not own:
            return ""
        return f"{np.mean(own) - np.mean(reference):+.3f}"

    header = ["Experiment", "Split", "Runs", "Owner", "2D val Dice", "Δ 2D", "3D Dice", "Δ 3D"] \
        + [f"3D {o}" for o in ORGANS] + ["Idea"]
    lines += ["Dice at the best epoch (chosen on 2D val Dice), mean over the 4 organs (± std over runs). "
              "Δ is against `current` on the same split.", "",
              "| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
    for key in sorted(groups):
        experiment, split = key
        members = groups[key]
        cells = [experiment, split, str(len(members)), members[0].get("owner") or "",
                 fmt([s["val_dice_2d"] for s in members]), delta(key, lambda s: s["val_dice_2d"]),
                 fmt([dice_3d(s) for s in members]), delta(key, dice_3d)]
        cells += [fmt([dice_3d(s, o) for s in members]) for o in ORGANS]
        cells += [members[0].get("idea") or ""]
        lines.append("| " + " | ".join(cells) + " |")

    header = ["Experiment", "Run", "2D val Dice", "3D Dice", "Best epoch", "Minutes", "Commit", "Device"]
    lines += ["", "## Runs", "", "| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
    for s in sorted(runs, key=lambda r: (r["experiment"], r["run"])):
        git = s.get("git") or {}
        commit = f"{git.get('commit')}{'*' if git.get('dirty') else ''}"
        lines.append("| " + " | ".join([s["experiment"], s["run"], fmt([s["val_dice_2d"]]), fmt([dice_3d(s)]),
                                        f"{s['best_epoch']} / {s['epochs']}", str(s["train_minutes"]),
                                        commit, s["device"]]) + " |")
    lines += ["", "`*` = run made with uncommitted changes.", ""]
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Compare runs and write RESULTS.md")
    parser.add_argument("--results", type=Path, default=Path("results"))
    parser.add_argument("--output", type=Path, default=Path("RESULTS.md"))
    parser.add_argument("--include-debug", action="store_true")
    args = parser.parse_args()

    runs = load_runs(args.results, args.include_debug)
    args.output.write_text(build_report(runs))
    print(f"> Wrote {args.output} ({len(runs)} runs)")


if __name__ == "__main__":
    main()
