name: ai4mi
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
    - torch
    - numpy
    - nibabel
    - torchvision
    - tqdm
    - pillow
    - scikit-image
    - matplotlib
    - wandb # will have to remove this at final submission time