import nibabel as nib
import numpy as np
import subprocess
import os
import shutil
import glob
from scipy.ndimage import distance_transform_edt

base_data_dir = "data/segthor_part1/train"
cleaned_data_dir = "data/segthor_part1_cleaned/train"


os.makedirs(cleaned_data_dir, exist_ok=True)

patient_dirs = sorted(glob.glob(os.path.join(base_data_dir, "Patient_*")))

# Merged green segment is Segment_1
merged_label_id = 1 
new_aorta_id = 1       # Keep aorta as 1
new_esophagus_id = 4   # Assign a new ID for the esophagus (since 1, 2, 3 are taken)

for patient_dir in patient_dirs:

    patient_id = os.path.basename(patient_dir)

    # Original paths
    ct_scan_path = os.path.join(patient_dir, f"{patient_id}.nii.gz")
    buggy_gt_path = os.path.join(patient_dir, "GT.nii.gz")
    ts_output_dir = os.path.join(patient_dir, "ts_temp_masks") # Temporary directory for TotalSegmentator

    # New cleaned paths
    patient_cleaned_dir = os.path.join(cleaned_data_dir, patient_id)
    cleaned_ct_path = os.path.join(patient_cleaned_dir, f"{patient_id}.nii.gz")
    cleaned_gt_path = os.path.join(patient_cleaned_dir, "GT.nii.gz")

    # Check if the required source files exist before proceeding
    if not os.path.exists(ct_scan_path) or not os.path.exists(buggy_gt_path):
        print(f"  Missing CT or GT for {patient_id}. Skipping.", flush=True)
        continue
        
    os.makedirs(ts_output_dir, exist_ok=True)
    os.makedirs(patient_cleaned_dir, exist_ok=True)

    try:
        print(f"Starting fixing {patient_id}", flush=True)
        # 1. Generate isolated masks for aorta and esophagus using the original CT
        os.makedirs(ts_output_dir, exist_ok=True)

        subprocess.run([
            "TotalSegmentator", "-i", ct_scan_path, 
            "-o", ts_output_dir, 
            "-d", "gpu:0", #"--fast", # Disable/enable when using GPU/CPU
            "--roi_subset", "aorta", "esophagus"
        ], check=True)

        # 2. Load the buggy ground truth volume
        gt_img = nib.load(buggy_gt_path)
        gt_data = gt_img.get_fdata()

        # 3. Load the new binary masks generated by TotalSegmentator
        aorta_mask_path = os.path.join(ts_output_dir, "aorta.nii.gz")
        esophagus_mask_path = os.path.join(ts_output_dir, "esophagus.nii.gz")

        if os.path.exists(aorta_mask_path) and os.path.exists(esophagus_mask_path):
            aorta_mask = nib.load(aorta_mask_path).get_fdata()
            esophagus_mask = nib.load(esophagus_mask_path).get_fdata()

            # 4. Only relabel voxels that carry the merged label in the original ground truth
            merged = gt_data == merged_label_id
            if not aorta_mask.any() or not esophagus_mask.any():
                raise ValueError("TotalSegmentator returned an empty aorta or esophagus mask")

            # 5. Assign each merged voxel to the nearest predicted structure (distance in mm)
            spacing = gt_img.header.get_zooms()[:3]
            dist_aorta = distance_transform_edt(aorta_mask == 0, sampling=spacing)
            dist_esophagus = distance_transform_edt(esophagus_mask == 0, sampling=spacing)
            gt_data[merged & (dist_aorta <= dist_esophagus)] = new_aorta_id
            gt_data[merged & (dist_esophagus < dist_aorta)] = new_esophagus_id
            
            # 6. Save the corrected ground truth with the original affine and header
            fixed_img = nib.Nifti1Image(gt_data.astype(np.uint8), gt_img.affine, gt_img.header)
            nib.save(fixed_img, cleaned_gt_path)
            print(f"Saved fixed ground truth for {patient_id}", flush=True)

            # 7. Copy the original CT scan to the new folder
            shutil.copy2(ct_scan_path, cleaned_ct_path)
        else:
            print(f"Failed to output expected masks for {patient_id}", flush=True)


    except Exception as e:
        print(f"Error for {patient_id}: {e}", flush=True)

    finally:
        # Clean up temporary TotalSegmentator output
        if os.path.exists(ts_output_dir):
            shutil.rmtree(ts_output_dir)

print("Dataset cleaning and transfer complete!", flush=True)