#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=VMUNet
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=00:10:00
#SBATCH --output=slurm_out/VMUNet_%A.out

module purge
module load 2023
module load Miniconda3/23.5.2-0
module load CUDA/12.1.1

source ai4mi2/bin/activate

# python -m pip install -r requirements.txt

python main_pep.py --dataset SEGTHOR --model VMUNet --mode full --epoch 25 --dest results/SEGTHOR/ce --gpu