#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=train_baseline
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=00:25:00
#SBATCH --output=jobs/outputs/train_baseline_output%A.out

module purge
module load 2023
source ai4mi/bin/activate

cd $HOME/SegTHOR_ai4mi
python -O main.py \
    --dataset SEGTHOR \
    --mode full \
    --epoch 25 \
    --dest results/segthor/ce \
    --gpu